### ISSUE TITLE
error writing grammar tables

### ISSUE THREAD

**Issue by jhgoebbert** [ryantam626/jupyterlab_code_formatter#82] opened 2019-11-05 20:49 UTC
I get an error upon launching Jupyter Lab with this extension enabled:

```
Generating grammar tables from /usr/local/software/jureca/Stages/Devel-2019a/software/Jupyter/2019a-rc19-gcccoremkl-8.3.0-2019.3.199-Python-3.6.8/lib/python3.6/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /p/project/cjsc/goebbert1/.cache/black/19.10b0/Grammar3.6.8.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/p/project/cjsc/goebbert1/.cache/black/19.10b0/tmpxebasypj'
Generating grammar tables from /usr/local/software/jureca/Stages/Devel-2019a/software/Jupyter/2019a-rc19-gcccoremkl-8.3.0-2019.3.199-Python-3.6.8/lib/python3.6/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /p/project/cjsc/goebbert1/.cache/black/19.10b0/PatternGrammar3.6.8.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/p/project/cjsc/goebbert1/.cache/black/19.10b0/tmp0pihfitq'
```

This error appears with black 19.10b0 on CentOS 7.6.

**Comment by jhgoebbert** [comment] 2019-11-06 08:32
This is the same as https://github.com/ryantam626/jupyterlab_code_formatter/issues/10 but for Linux, which was closed without a general fix but only a workaround for a single user.

**Comment by ryantam626** [comment] 2019-12-01 18:48
Hello! Sorry for the delay in replying, have been very busy with other stuff.

Hmm yes. I won't be fixing this, I believe this is just out of the scope of this plugin. The user starting jupyterlab should create the directory manually if there is some sort of permission issue.

**Closed by ryantam626** 2019-12-01 18:48 UTC

**Comment by AlJohri** [comment] 2020-01-08 00:47
Here is the root cause for the error on the black side: https://github.com/psf/black/issues/1223

**Comment by antonkulaga** [comment] 2020-05-28 16:39
@AlJohri why did you close it (the bug is still valid for me with latest versions of jupyter lab)? Even if it is an upstream bug in black, it is better to keep it opened until black guys will fix the bug and you will update the dependency

**Comment by AlJohri** [comment] 2020-05-28 16:46
@antonkulaga I didn't close it. If you want, you can try to follow up on this PR to get this fixed: https://github.com/psf/black/pull/1224
