### ISSUE TITLE
jupyterlab_code_formatter not showing on Jupyterlab 2.0.2

### ISSUE THREAD

**Issue by thomaspernet** [ryantam626/jupyterlab_code_formatter#130] opened 2020-03-26 10:08 UTC
@ryantam626  It seems the issue is not solved for Jupyterlab 2.0.2.  I added the `pip freeze`, sorry ..

I updated all the extensions and jupyterlab_code_formatter isn't showing on the left panel. jupyterlab_code_formatter is available in the labextension and server. I use `autopep8` 

- `pip freeze`

```
absl-py==0.9.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
ansiwrap==0.8.4
appdirs==1.4.3
appnope==0.1.0
appscript==1.1.0
arch==4.11
asn1crypto==1.2.0
astor==0.8.1
astroid==2.3.3
astropy==3.2.3
atomicwrites==1.3.0
attrs==19.3.0
auto-load==0.1
auto-nb==0.1
autopep8==1.4.4
awscli==1.18.21
awsPy==0.1
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.8.1
bitarray==1.1.0
bkcharts==0.2
black==19.10b0
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
boto3==1.12.0
botocore==1.15.21
Bottleneck==1.3.1
cachetools==3.1.1
camelot-py==0.7.3
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
clyent==1.2.2
colorama==0.4.1
conda==4.8.3
conda-build==3.18.10
conda-package-handling==1.6.0
conda-verify==3.4.2
confuse==1.0.0
contextlib2==0.6.0.post1
CorrespondenceAnalysisPy==0.2
cryptography==2.8
cycler==0.10.0
Cython==0.29.14
cytoolz==0.10.1
dash==1.9.0
dash-core-components==1.8.0
dash-html-components==1.0.2
dash-renderer==1.2.4
dash-table==4.6.0
dask==2.8.1
DataAnalysis==0.5
dautil==0.0.1b2
decorator==4.4.1
defusedxml==0.6.0
distributed==2.8.1
distro==1.4.0
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
Fast-connectCloud==0.10
fastcache==1.1.0
fasteners==0.14.1
feather-format==0.4.0
filelock==3.0.10
Flask==1.1.1
Flask-Compress==1.4.0
fsspec==0.6.1
future==0.18.2
gast==0.2.2
gevent==1.4.0
ghostscript==0.6
gitdb2==2.0.6
GitPython==3.0.3
glob2==0.7
gmpy2==2.1.0b1
google-api-core==1.14.3
google-api-python-client==1.7.11
google-auth==1.6.3
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-cloud-bigquery==1.21.0
google-cloud-core==1.0.3
google-cloud-storage==1.20.0
google-pasta==0.1.8
google-resumable-media==0.4.1
googleapis-common-protos==1.6.0
GoogleDrivePy==0.3
greenlet==0.4.15
grequests==0.4.0
grpcio==1.26.0
h5py==2.10.0
HeapDict==1.0.1
hide-code==0.5.2
html5lib==1.0.1
htmlmin==0.1.12
httplib2==0.14.0
idna==2.8
imageio==2.6.1
imagesize==1.1.0
importlib-metadata==1.5.2
ipykernel==5.1.3
ipython==7.10.0
ipython-genutils==0.2.0
ipyupload==0.1.3
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.15.1
Jinja2==2.10.3
jmespath==0.9.4
joblib==0.14.0
jplephem==2.9
json5==0.8.5
jsonschema==3.2.0
jupyter-client==5.3.3
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==2.0.1
jupyterlab-code-formatter==1.2.2
jupyterlab-git==0.8.1
jupyterlab-github==1.0.0
jupyterlab-latex==1.0.0
jupyterlab-server==1.0.6
jupytext==1.4.0+dev
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==19.2.0
kiwisolver==1.1.0
landslide==1.1.6
lazy-object-proxy==1.4.3
libarchive-c==2.9
lief==0.9.0
llvmlite==0.30.0
locket==0.2.0
lunardate==0.2.0
lxml==4.4.1
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==3.0.5
monotonic==1.5
more-itertools==7.2.0
mpmath==1.1.0
msgpack==0.6.2
multipledispatch==0.6.0
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbconvert==5.6.1
nbdime==1.1.0
nbformat==4.4.0
networkx==2.4
nltk==3.4.4
nodejs==0.1.1
nose==1.3.7
notebook==6.0.1
notebook-creator==0.1
numba==0.46.0
numexpr==2.7.0
numpy==1.17.4
numpydoc==0.9.1
oauth2client==4.1.3
oauthlib==3.1.0
olefile==0.46
opencv-python==4.1.2.30
openpyxl==3.0.2
opt-einsum==3.1.0
optional-django==0.1.0
packaging==20.1
pandas==0.25.3
pandas-profiling==2.3.0
pandocfilters==1.4.2
papermill==1.2.1
parso==0.5.1
partd==1.0.0
path.py==12.0.2
pathlib2==2.3.5
pathspec==0.7.0
patool==1.12
patsy==0.5.1
pdfkit==0.6.1
pdfminer.six==20191110
pep8==1.7.1
pexpect==4.7.0
phik==0.9.8
pickleshare==0.7.5
Pillow==6.2.1
pinyin==0.4.0
pivottablejs==0.9.0
pkginfo==1.5.0.1
plotly==4.0.0
pluggy==0.12.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==2.0.10
property-cached==1.6.3
protobuf==3.10.0
protobuf3-to-dict==0.1.5
psutil==5.6.7
ptyprocess==0.6.0
py==1.8.0
pyarrow==0.15.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
PyAthena==1.10.2
pyCalverter==1.6.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycryptodome==3.9.4
pycurl==7.43.0.3
pydot==1.4.1
pydotplus==2.0.2
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
pyluach==1.0.1
pymongo==3.10.0
pyodbc==4.0.27
pyOpenSSL==19.0.0
pyparsing==2.4.5
PyPDF2==1.26.0
pyrsistent==0.15.6
PySocks==1.7.1
pytest==5.3.1
pytest-arraydiff==0.3
pytest-astropy==0.6.0
pytest-astropy-header==0.1.1
pytest-doctestplus==0.4.0
pytest-openfiles==0.4.0
pytest-pylint==0.14.1
pytest-remotedata==0.3.1
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.1.2
pyzmq==18.1.1
qgrid==1.1.1
QtAwesome==0.6.0
qtconsole==4.6.0
QtPy==1.9.0
regex==2020.2.20
requests==2.22.0
requests-oauthlib==1.2.0
researchpy==0.1.7
retrying==1.3.3
rise==5.6.0
rope==0.14.0
rsa==3.4.2
ruamel-yaml==0.15.46
s3fs==0.4.0
s3transfer==0.3.3
sagemaker==1.50.17
scikit-image==0.16.2
scikit-learn==0.21.3
scipy==1.4.1
seaborn==0.9.0
Send2Trash==1.5.0
sgp4==1.4
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.13.0
skyfield==1.15
skyfield-data==0.1.0
smdebug-rulesconfig==0.1.2
smmap2==2.0.5
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
sos==0.20.8
sos-notebook==0.20.6
sos-papermill==0.1.6
sos-pbs==0.20.1
sos-r==0.19.2
soupsieve==1.9.4
Sphinx==2.2.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.2
SQLAlchemy==1.3.11
squarify==0.4.3
statsmodels==0.10.2
style==1.1.0
sympy==1.4
tables==3.6.1
tabula-py==1.4.2
tabulate==0.8.6
tblib==1.4.0
tenacity==6.0.0
tensorboard==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
textwrap3==0.9.2
tika==1.22
tkcalendar==1.6.1
toml==0.10.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.39.0
TradeGecko-API==0.1
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.1
unicodecsv==0.14.1
unrar==0.4
update==0.0.1
uritemplate==3.0.0
urllib3==1.25.7
wbdata==0.2.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
workalendar==7.1.0
wrapt==1.11.2
wurlitzer==1.0.3
xlrd==1.2.0
XlsxWriter==1.2.6
xlwings==0.16.0
xlwt==1.3.0
xxhash==1.4.1
zict==1.0.0
zipp==0.6.0
```

- `jupyter labextension list`

```
JupyterLab v2.0.1
Known labextensions:
   app dir: /Users/thomas/anaconda3/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/github v2.0.0 disabled OK
        @jupyterlab/latex v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.2.2  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        jupyterlab-jupytext v1.2.1  enabled  OK
        jupyterlab-sos v0.6.1  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
        qgrid v1.1.1  enabled  OK
        transient-display-data v0.4.0  enabled  OK
```
- `jupyter serverextension list`

```
config dir: /Users/thomas/.jupyter
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git  OK
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
    jupyter_nbextensions_configurator  enabled 
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 OK
    hide_code  enabled 
    - Validating...
      hide_code  OK
config dir: /Users/thomas/anaconda3/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.0.1 OK
    jupyterlab_github  enabled 
    - Validating...
      jupyterlab_github 1.0.0 OK
    jupyterlab_latex  enabled 
    - Validating...
      jupyterlab_latex 1.0.0 OK
    jupytext  enabled 
    - Validating...
      jupytext 1.4.0+dev OK
    nbdime  enabled 
    - Validating...
      nbdime 1.1.0 OK
```

**Comment by ryantam626** [comment] 2020-03-26 10:24
i need output of `pip freeze` as documented in the issue template :)

**Comment by ryantam626** [comment] 2020-03-26 13:52
everything seems to be alright :thinking: is there anything on the web console of your browser or the terminal you started jupyterlab?

**Comment by thomaspernet** [comment] 2020-03-26 17:16
Yes, I don't know what's going on. here is the log when I launch Jupyterlab

```
(base) thomas@x86_64-apple-darwin13 ~ % jupyter lab
[I 18:15:41.825 LabApp] hide_code: Attempting to load hid_code export handler extensions.
[I 18:15:41.827 LabApp] hide_code: Hide_code export handler extensions loaded.
[I 18:15:41.853 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 18:15:42.562 LabApp] JupyterLab extension loaded from /Users/thomas/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 18:15:42.562 LabApp] JupyterLab application directory is /Users/thomas/anaconda3/share/jupyter/lab
[I 18:15:42.955 LabApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 18:15:43.286 LabApp] Serving notebooks from local directory: /Users/thomas
[I 18:15:43.286 LabApp] The Jupyter Notebook is running at:
[I 18:15:43.286 LabApp] http://localhost:8888/?token=f0e5d1446b8d991475f4a2fa85b831110a24d73779fd8826
[I 18:15:43.286 LabApp]  or http://127.0.0.1:8888/?token=f0e5d1446b8d991475f4a2fa85b831110a24d73779fd8826
[I 18:15:43.286 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:15:43.299 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/thomas/Library/Jupyter/runtime/nbserver-31628-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f0e5d1446b8d991475f4a2fa85b831110a24d73779fd8826
     or http://127.0.0.1:8888/?token=f0e5d1446b8d991475f4a2fa85b831110a24d73779fd8826
[I 18:15:48.160 LabApp] Build is up to date
```

**Comment by fishstoryyy** [comment] 2020-03-27 15:42
I have the same problem here.
And this shows up in the terminal when starting Jupyter Lab
`[W 11:37:06.130 LabApp] 422 GET /jupyterlab_code_formatter/formatters?1585323426080 (::1) 9.41ms referer=http://localhost:8889/lab`

**Comment by ryantam626** [comment] 2020-03-28 09:15
@fishstoryyy i don't believe you do, you have a generic version mismatch issue, try #119 or FAQ?

**Comment by ryantam626** [comment] 2020-03-28 09:25
@thomaspernet and there is nothing in the web console :cry: ?

**Comment by thomaspernet** [comment] 2020-03-28 14:38
@ryantam626  I'm not very familiar with the console, but it looks like nothing is wrong

<img width="894" alt="Screenshot 2020-03-28 at 15 36 45" src="https://user-images.githubusercontent.com/33351426/77825512-17bb8b80-710a-11ea-93ca-8da957aa5e32.png">
<img width="894" alt="Screenshot 2020-03-28 at 15 36 37" src="https://user-images.githubusercontent.com/33351426/77825515-1ab67c00-710a-11ea-85c6-6e1e75c16ce9.png">

**Comment by jieyu-tech** [comment] 2020-04-03 15:05
same issue here. At first, it's an issue similiar with [Potential plugin version mismatch issue ](https://github.com/ryantam626/jupyterlab_code_formatter/issues/119), after I had fixed it by running: 
$ conda install -c conda-forge jupyterlab_code_formatter==1.1.0
instead of pip xxx

the error msg gone, but I can't use it yet, due to no command interface exposed.

Nothing shows at jupyterlab console. Not sure where can I get debug log.

By the way, it should  be a great extension, thanks!

with this extension and lsp, and maybe "code structure"(show methods, properties in a class), jupyterlab can be a wonderfull IDE.

**Comment by ryantam626** [comment] 2020-04-09 19:17
Hi all sorry I was AFK.

@thomaspernet actually the console log suggest there is something wrong with your jupyterlab installation, I have seen it a few time during the development of this plugin, I didn't figure out why but reinstall jupyterlab usually helps. :confused: 

@jieyu-tech the bug issue template has a few steps for how you can generate some debug info for easier diagnostic on my side, would you mind opening one (and attaching the info)?

**Comment by thomaspernet** [comment] 2020-04-18 05:17
@ryantam626  I reinstall jupyter lab, clean up jupyter la, upgrade but didn"t work

```
JupyterLab v2.1.0
Known labextensions:
   app dir: /Users/thomas/anaconda3/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.2.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/github v2.0.0 disabled OK
        @jupyterlab/latex v2.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.2.3  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        jupyterlab-jupytext v1.2.1  enabled  OK
        jupyterlab-sos v0.6.1  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
        qgrid v1.1.1  enabled  OK
        transient-display-data v0.4.0  enabled  OK
```

and 

```
Extension 'jupyterlab-sos' already up to date
Extension '@jupyterlab/latex' already up to date
Extension 'qgrid' already up to date
Extension '@jupyterlab/github' already up to date
Extension 'nbdime-jupyterlab' already up to date
Extension '@jupyterlab/toc' already up to date
Extension 'transient-display-data' already up to date
Extension '@ryantam626/jupyterlab_code_formatter' already up to date
Extension 'jupyterlab-jupytext' already up to date
Extension '@aquirdturtle/collapsible_headings' already up to date
Extension 'jupyter-matplotlib' already up to date
Extension '@jupyter-widgets/jupyterlab-manager' already up to date
```

**Comment by ryantam626** [comment] 2020-04-18 09:47
@thomaspernet 
Are you using a Python notebook?

**Comment by thomaspernet** [comment] 2020-04-29 08:08
Yes, I use Python Notebook. I haven't tried on an EC2 instance if `jupyterlab_code_formatter` woks. I tried on a Windows machine at work and got the same issue. `jupyterlab_code_formatter` is not showing

**Comment by ryantam626** [comment] 2020-04-30 07:45
can you try install just this plugin and see if it works?
you have quite a lot of plugin enabled and i am not sure if some other plugin is some how interfering, isolating the cause would make determining the issue easier.

as it stands right now, i can't debug this because there just isn't enough information for me to work with, all the other common issues people face have more or less been ruled out.

**Comment by ryantam626** [comment] 2020-04-30 07:49
are you sure you are not using sos notebook?

**Comment by thomaspernet** [comment] 2020-04-30 16:33
I will test on an EC2 instance, see if it works or not. I will only install `jupyterlab_code_formatter`.

SOS notebook is not the default kernel. When I try, it's usually with Python Kernel, not SOS

**Comment by thomaspernet** [comment] 2020-05-06 05:41
So I removed Anaconda, and install a fresh new one. I installed only `jupyterlab_code_formatter` following your instructions, and it worked! I keep installing other different extensions. It also worked. So everything is okay now. 

Can't tell why Jupyterlab was broken before. Anyway, thanks for your great plugin!

Steps done

```
(base) thomas@Thomass-MacBook-Pro ~ % conda --version
conda 4.8.3
(base) thomas@Thomass-MacBook-Pro ~ % conda install black nodejs
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/thomas/anaconda3

  added / updated specs:
    - black
    - nodejs


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    appdirs-1.4.3              |   py37h28b3542_0          15 KB
    black-19.10b0              |             py_0          86 KB
    mypy_extensions-0.4.3      |           py37_0           9 KB
    nodejs-10.13.0             |       h0a44026_0        11.7 MB
    pathspec-0.7.0             |             py_0          26 KB
    regex-2020.4.4             |   py37h1de35cc_0         310 KB
    ------------------------------------------------------------
                                           Total:        12.2 MB

The following NEW packages will be INSTALLED:

  appdirs            pkgs/main/osx-64::appdirs-1.4.3-py37h28b3542_0
  black              pkgs/main/noarch::black-19.10b0-py_0
  mypy_extensions    pkgs/main/osx-64::mypy_extensions-0.4.3-py37_0
  nodejs             pkgs/main/osx-64::nodejs-10.13.0-h0a44026_0
  pathspec           pkgs/main/noarch::pathspec-0.7.0-py_0
  regex              pkgs/main/osx-64::regex-2020.4.4-py37h1de35cc_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
mypy_extensions-0.4. | 9 KB      | ######################################################################### | 100% 
nodejs-10.13.0       | 11.7 MB   | ######################################################################### | 100% 
regex-2020.4.4       | 310 KB    | ######################################################################### | 100% 
appdirs-1.4.3        | 15 KB     | ######################################################################### | 100% 
black-19.10b0        | 86 KB     | ######################################################################### | 100% 
pathspec-0.7.0       | 26 KB     | ######################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) thomas@Thomass-MacBook-Pro ~ % jupyter labextension install @ryantam626/jupyterlab_code_formatter
Building jupyterlab assets (build:prod:minimize)
(base) thomas@Thomass-MacBook-Pro ~ % conda install -c conda-forge jupyterlab_code_formatter
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/thomas/anaconda3

  added / updated specs:
    - jupyterlab_code_formatter


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    certifi-2020.4.5.1         |   py37hc8dfbb8_0         151 KB  conda-forge
    conda-4.8.3                |   py37hc8dfbb8_1         3.0 MB  conda-forge
    jupyterlab_code_formatter-1.2.5|             py_0           8 KB  conda-forge
    openssl-1.1.1g             |       h0b31af3_0         1.9 MB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.2 MB

The following NEW packages will be INSTALLED:

  jupyterlab_code_f~ conda-forge/noarch::jupyterlab_code_formatter-1.2.5-py_0
  python_abi         conda-forge/osx-64::python_abi-3.7-1_cp37m

The following packages will be UPDATED:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2020.4.5.1-hecc5488_0
  conda                       pkgs/main::conda-4.8.3-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi              pkgs/main::certifi-2020.4.5.1-py37_0 --> conda-forge::certifi-2020.4.5.1-py37hc8dfbb8_0
  openssl              pkgs/main::openssl-1.1.1g-h1de35cc_0 --> conda-forge::openssl-1.1.1g-h0b31af3_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
ca-certificates-2020 | 146 KB    | ######################################################################### | 100% 
conda-4.8.3          | 3.0 MB    | ######################################################################### | 100% 
python_abi-3.7       | 4 KB      | ######################################################################### | 100% 
certifi-2020.4.5.1   | 151 KB    | ######################################################################### | 100% 
openssl-1.1.1g       | 1.9 MB    | ######################################################################### | 100% 
jupyterlab_code_form | 8 KB      | ######################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) thomas@Thomass-MacBook-Pro ~ % jupyter serverextension enable --py jupyterlab_code_formatter
Enabling: jupyterlab_code_formatter
- Writing config: /Users/thomas/.jupyter
    - Validating...
      jupyterlab_code_formatter  OK
(base) thomas@Thomass-MacBook-Pro ~ % conda install black
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/thomas/anaconda3

  added / updated specs:
    - black


The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    conda-forge::ca-certificates-2020.4.5~ --> pkgs/main::ca-certificates-2020.1.1-0
  certifi            conda-forge::certifi-2020.4.5.1-py37h~ --> pkgs/main::certifi-2020.4.5.1-py37_0
  conda              conda-forge::conda-4.8.3-py37hc8dfbb8~ --> pkgs/main::conda-4.8.3-py37_0
  openssl            conda-forge::openssl-1.1.1g-h0b31af3_0 --> pkgs/main::openssl-1.1.1g-h1de35cc_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) thomas@Thomass-MacBook-Pro ~ % conda install -c conda-forge jupyterlab
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/thomas/anaconda3

  added / updated specs:
    - jupyterlab


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jupyterlab-2.1.2           |             py_0         6.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.1 MB

The following packages will be UPDATED:

  ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2020.4.5.1-hecc5488_0
  conda                       pkgs/main::conda-4.8.3-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1
  jupyterlab         pkgs/main::jupyterlab-1.2.6-pyhf63ae9~ --> conda-forge::jupyterlab-2.1.2-py_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi              pkgs/main::certifi-2020.4.5.1-py37_0 --> conda-forge::certifi-2020.4.5.1-py37hc8dfbb8_0
  openssl              pkgs/main::openssl-1.1.1g-h1de35cc_0 --> conda-forge::openssl-1.1.1g-h0b31af3_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
jupyterlab-2.1.2     | 6.1 MB    | ################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) thomas@Thomass-MacBook-Pro ~ % jupyter labextension list
JupyterLab v2.1.2
Known labextensions:
   app dir: /Users/thomas/anaconda3/share/jupyter/lab
        @ryantam626/jupyterlab_code_formatter v1.2.5  enabled  OK
```

**Comment by ryantam626** [comment] 2020-05-11 08:24
it's possible there might be something leftover when you first reinstalled jupyter lab :thinking: but i don't know what that might be..

and yes, the message you posted is safe to ignore, that's what the `black` formatter spits out when it's ran the first time.

**Comment by ryantam626** [comment] 2020-05-11 08:24
anyway, since this is working now, i will be closing this for now :+1:

**Closed by ryantam626** 2020-05-11 08:24 UTC
